version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/core"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/compiler-tests"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "tsdoc"
    schedule:
      interval: "daily"
