baseurl: /xunit.ts
defaults:
  - scope:
      path: ""
    values:
      layout: index
      permalink: :basename/
  - scope:
      path: "Assertions"
    values:
      permalink: Assertions/:basename/